%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.16.0

-ifndef(messages).
-define(messages, true).

-define(messages_gpb_version, "4.16.0").

-ifndef('MESSAGE_PB_H').
-define('MESSAGE_PB_H', true).
-record('Message',
        {type                   :: 'REGISTER' | 'LOGIN' | 'LOGOUT' | 'REPLY' | 'LOCATION' | 'SICK' | 'NR_PEOPLE' | integer() | undefined, % = 1, required, enum Type
         register               :: messages:'Register'() | undefined, % = 2, optional
         login                  :: messages:'Login'() | undefined, % = 3, optional
         reply                  :: messages:'Reply'() | undefined, % = 4, optional
         location               :: messages:'Location'() | undefined % = 5, optional
        }).
-endif.

-ifndef('REGISTER_PB_H').
-define('REGISTER_PB_H', true).
-record('Register',
        {username               :: iodata() | undefined, % = 1, required
         password               :: iodata() | undefined, % = 2, required
         district               :: iodata() | undefined % = 3, required
        }).
-endif.

-ifndef('LOGIN_PB_H').
-define('LOGIN_PB_H', true).
-record('Login',
        {username               :: iodata() | undefined, % = 1, required
         password               :: iodata() | undefined % = 2, required
        }).
-endif.

-ifndef('REPLY_PB_H').
-define('REPLY_PB_H', true).
-record('Reply',
        {result                 :: boolean() | 0 | 1 | undefined, % = 1, required
         message                :: iodata() | undefined % = 2, required
        }).
-endif.

-ifndef('LOCATION_PB_H').
-define('LOCATION_PB_H', true).
-record('Location',
        {coordx                 :: integer() | undefined, % = 1, required, 32 bits
         coordy                 :: integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-endif.
