%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.16.0

-ifndef(messages).
-define(messages, true).

-define(messages_gpb_version, "4.16.0").

-ifndef('REPLY_PB_H').
-define('REPLY_PB_H', true).
-record('Reply',
        {result                 :: boolean() | 0 | 1 | undefined, % = 1, required
         message                :: iodata() | undefined % = 2, required
        }).
-endif.

-ifndef('MESSAGE_PB_H').
-define('MESSAGE_PB_H', true).
-record('Message',
        {type                   :: 'REGISTER' | 'LOGIN' | 'LOGOUT' | 'REPLY' | 'LOCATION' | 'SICK' | integer() | undefined, % = 1, required, enum Type
         registerData           :: messages:'Register'() | undefined, % = 2, optional
         loginData              :: messages:'Login'() | undefined, % = 3, optional
         logoutData             :: messages:'Logout'() | undefined, % = 4, optional
         replyData              :: messages:'Reply'() | undefined % = 5, optional
        }).
-endif.

-ifndef('REGISTER_PB_H').
-define('REGISTER_PB_H', true).
-record('Register',
        {username               :: iodata() | undefined, % = 1, required
         password               :: iodata() | undefined, % = 2, required
         district               :: iodata() | undefined % = 3, required
        }).
-endif.

-ifndef('LOGIN_PB_H').
-define('LOGIN_PB_H', true).
-record('Login',
        {username               :: iodata() | undefined, % = 1, required
         password               :: iodata() | undefined % = 2, required
        }).
-endif.

-ifndef('LOGOUT_PB_H').
-define('LOGOUT_PB_H', true).
-record('Logout',
        {username               :: iodata() | undefined, % = 1, required
         password               :: iodata() | undefined % = 2, required
        }).
-endif.

-endif.
